FROM node:20-alpine 
# RUN apk add --no-cache make gcc g++ python2
ENV NODE_ENV=dev 

WORKDIR /app
COPY ./package*.json /app/
COPY .env.local .env

RUN npm install
COPY . /app

# Expose the port the app runs in
EXPOSE 3000

# Serve the app
CMD npm run dev
